In [1]:
import pandas as pd

file_path = "../data/sample/yellow_tripdata_2025-07.parquet"

df = pd.read_parquet(file_path)

df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,2025-07-01 00:29:37,2025-07-01 00:45:30,1.0,7.30,1.0,N,138,74,1,29.6,7.75,0.5,9.00,6.94,1.0,54.79,0.0,1.75,0.00
1,1,2025-07-01 00:23:28,2025-07-01 01:07:44,1.0,17.70,2.0,N,132,142,1,70.0,4.25,0.5,5.00,0.00,1.0,80.75,2.5,1.75,0.00
2,2,2025-07-01 00:53:50,2025-07-01 01:27:12,1.0,9.98,1.0,N,138,48,1,43.6,6.00,0.5,10.87,0.00,1.0,66.97,2.5,1.75,0.75
3,2,2025-07-01 00:58:49,2025-07-01 01:15:55,1.0,10.27,1.0,N,138,229,1,38.7,6.00,0.5,14.10,6.94,1.0,72.24,2.5,1.75,0.75
4,2,2025-07-01 00:09:22,2025-07-01 00:23:54,1.0,2.94,1.0,N,211,97,1,17.0,1.00,0.5,3.00,0.00,1.0,25.75,2.5,0.00,0.75

In [2]:
df.shape

(3898963, 20)

In [3]:
df.columns

Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag',
       'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount', 'congestion_surcharge', 'Airport_fee',
       'cbd_congestion_fee'],
      dtype='object')

In [4]:
df.dtypes

VendorID                          int32
tpep_pickup_datetime     datetime64[us]
tpep_dropoff_datetime    datetime64[us]
passenger_count                 float64
trip_distance                   float64
RatecodeID                      float64
store_and_fwd_flag               object
PULocationID                      int32
DOLocationID                      int32
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
Airport_fee                     float64
cbd_congestion_fee              float64
dtype: object

In [5]:
df.isnull().sum()

VendorID                       0
tpep_pickup_datetime           0
tpep_dropoff_datetime          0
passenger_count          1038755
trip_distance                  0
RatecodeID               1038755
store_and_fwd_flag       1038755
PULocationID                   0
DOLocationID                   0
payment_type                   0
fare_amount                    0
extra                          0
mta_tax                        0
tip_amount                     0
tolls_amount                   0
improvement_surcharge          0
total_amount                   0
congestion_surcharge     1038755
Airport_fee              1038755
cbd_congestion_fee             0
dtype: int64

In [6]:
df.describe()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
count,3.898963e+06,3898963,3898963,2.860208e+06,3.898963e+06,2.860208e+06,3.898963e+06,3.898963e+06,3.898963e+06,3.898963e+06,3.898963e+06,3.898963e+06,3.898963e+06,3.898963e+06,3.898963e+06,3.898963e+06,2.860208e+06,2.860208e+06,3.898963e+06
mean,1.887506e+00,2025-07-17 04:53:36.198563,2025-07-17 05:10:42.166691,1.315910e+00,7.104756e+00,3.005781e+00,1.593296e+02,1.590559e+02,9.270137e-01,1.854769e+01,1.107153e+00,4.758367e-01,2.686127e+00,5.004544e-01,9.459860e-01,2.682744e+01,2.145727e+00,1.587607e-01,5.356467e-01
min,1.000000e+00,2009-01-01 08:52:26,2009-01-01 10:00:26,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,-1.591300e+03,-7.500000e+00,-5.000000e-01,-5.275000e+01,-1.128400e+02,-1.000000e+00,-1.634750e+03,-2.500000e+00,-1.750000e+00,-7.500000e-01
25%,2.000000e+00,2025-07-09 20:58:59,2025-07-09 21:12:59,1.000000e+00,1.060000e+00,1.000000e+00,1.140000e+02,1.070000e+02,0.000000e+00,8.820000e+00,0.000000e+00,5.000000e-01,0.000000e+00,0.000000e+00,1.000000e+00,1.580000e+01,2.500000e+00,0.000000e+00,0.000000e+00
50%,2.000000e+00,2025-07-17 09:48:52,2025-07-17 10:07:44,1.000000e+00,1.910000e+00,1.000000e+00,1.610000e+02,1.610000e+02,1.000000e+00,1.420000e+01,0.000000e+00,5.000000e-01,2.000000e+00,0.000000e+00,1.000000e+00,2.142000e+01,2.500000e+00,0.000000e+00,7.500000e-01
75%,2.000000e+00,2025-07-24 19:51:14.500000,2025-07-24 20:08:03,1.000000e+00,3.900000e+00,1.000000e+00,2.300000e+02,2.310000e+02,1.000000e+00,2.330000e+01,2.500000e+00,5.000000e-01,3.850000e+00,0.000000e+00,1.000000e+00,3.078000e+01,2.500000e+00,0.000000e+00,7.500000e-01
max,7.000000e+00,2025-07-31 23:59:59,2025-08-03 17:03:02,9.000000e+00,3.979944e+05,9.900000e+01,2.650000e+02,2.650000e+02,4.000000e+00,2.495000e+03,1.500000e+01,5.243380e+03,5.000000e+02,2.041800e+02,1.000000e+00,5.297870e+03,2.500000e+00,6.750000e+00,1.500000e+00
std,7.337028e-01,NaN,NaN,7.589974e-01,6.700148e+02,1.349034e+01,6.624882e+01,7.062472e+01,7.939307e-01,2.007138e+01,1.803865e+00,2.659264e+00,3.935143e+00,2.132647e+00,3.001838e-01,2.427461e+01,1.008222e+00,5.558867e-01,3.599308e-01